codecov:
  branch: master       # the branch to show by default, inherited from your git repository settings
                       # ex. master, stable or release
                       # default: the default branch in git/mercurial
coverage:
  precision: 2         # how many decimal places to display in the UI: 0 <= value <= 4
  round: down          # how coverage is rounded: down/up/nearest
  range: 50...100      # custom range of coverage colors from red -> yellow -> green

  status:

    patch:
      default:
        enabled: yes             # must be yes|true to enable this status
        threshold: 100          # allowed to drop X% and still result in a "success" commit status
        if_no_uploads: error     # will post commit status of "error" if no coverage reports we uploaded
        if_not_found: success
        if_ci_failed: error
