language: java
jdk:
  - oraclejdk9

script:
  - cd agile/ && mvn install
  - mvn cobertura:cobertura

# Upload coverage data to codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
