language: java
jdk:
  - oraclejdk9

before_install:
 - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - mvn install

# Upload coverage data to codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
